### ISSUE TITLE
Bamboo agent atlassian-bamboo-agent-installer.jar

### ISSUE THREAD

**Issue by ramyakailas** [ramonskie/bamboo#16]
I used both the bamboo::server and bamboo::agent recipes in the run list and i was bootstrapping a new server with these recipes.
bamboo::agent recipe would fail at the following step
```
execute "java -Ddisable_agent_auto_capability_detection=#{node[:bamboo][:agent][:disable_agent_auto_capability_detection]} -Dbamboo.home=#{node[:bamboo][:agent][:data_dir]} -jar #{node[:bamboo][:agent][:home_dir]}/atlassian-bamboo-agent-installer.jar #{node[:bamboo][:url]}/agentServer/ install" do
```

Due to incorrect atlassian-bamboo-agent-installer.jar , on further inestigation i found that the jar that was getting downloaded was incorrect without the version.

Can this be added to the recipe -
```
execute "java -Ddisable_agent_auto_capability_detection=#{node[:bamboo][:agent][:disable_agent_auto_capability_detection]} -Dbamboo.home=#{node[:bamboo][:agent][:data_dir]} -jar #{node[:bamboo][:agent][:home_dir]}/atlassian-bamboo-agent-installer-#{node[:bamboo][:version]}.jar #{node[:bamboo][:url]}/agentServer/ install" do
```

**Comment by ramonskie** [comment]
as you can see on https://github.com/ramonskie/bamboo/blob/master/recipes/agent.rb#L53
the jar is downloaded and renamed to atlassian-bamboo-agent-installer.jar
