### ISSUE TITLE
Some problem resolving dependencies 

### ISSUE THREAD

**Issue by timgriffiths** [ramonskie/bamboo#17]
Have no real idea what's going wrong here, but Librarian seems to have a lot of trouble pulling down this cookbook, i forked the project and just removed the version numbers (ie ~>1.2.8) from the metadata.rb and it all seems to flow though fine. so no real idea what's going wrong.

[Librarian] Resolving bamboo (>= 0) <https://github.com/ramonskie/bamboo.git#master>
[Librarian]   Checking manifests
[Librarian]     --- No output
[Librarian]     --- No output
[Librarian]     --> 4137ea4bed936e017ff62d4a3dcf8b5b81c1a997
[Librarian]     --- No output
[Librarian]     --- No output
[Librarian]     --> origin
[Librarian]     -->   origin/HEAD -> origin/master
[Librarian]     -->   origin/master
[Librarian]     --> 4137ea4bed936e017ff62d4a3dcf8b5b81c1a997
[Librarian]     --> 4137ea4bed936e017ff62d4a3dcf8b5b81c1a997
[Librarian]     --> 4137ea4bed936e017ff62d4a3dcf8b5b81c1a997
[Librarian]     Checking bamboo/1.4.0 <https://github.com/ramonskie/bamboo.git#master>
[Librarian]       Scheduling apache2 (>= 0.0.0) <https://github.com/viverae-cookbooks/apache2.git#master>
[Librarian]       Scheduling apt (>= 0.0.0) <(no source specified)>
[Librarian]       Scheduling ark (~> 0.9.0) <http://community.opscode.com/api/v1>
[Librarian]       Scheduling backup (~> 0.2.1) <https://github.com/damm/backup.git#master>
[Librarian]       Conflict between cron (~> 1.2.8) <https://github.com/opscode-cookbooks/cron.git#master> and cron/1.6.1 <https://github.com/opscode-cookbooks/cron.git#master>
[Librarian]       Backtracking from bamboo/1.4.0 <https://github.com/ramonskie/bamboo.git#master>
[Librarian]   Failed to resolve bamboo (>= 0) <https://github.com/ramonskie/bamboo.git#master>
Could not resolve the dependencies.

**Comment by ramonskie** [comment]
does this problem still occur?
