### ISSUE TITLE
git clone command is wrong, and there is no Vagrantfile

### ISSUE THREAD

**Issue by mrjcleaver** [ramonskie/bamboo#21]
````
Testing and Development

Here's how you can quickly get testing or developing against the cookbook thanks to Vagrant and Berkshelf.

git clone git://github.com/ramonskie/chef-bamboo.git
cd chef-bamboo
````

That's a better name for the repo, but not the one you chose!

**Comment by mrjcleaver** [comment]
Did we lose it?

**Comment by ramonskie** [comment]
i removed the vagrant file
because test-kitchen is the way to go

**Comment by ramonskie** [comment]
updated the readme
see https://github.com/ramonskie/bamboo/commit/1fb5130659b494a9ecdb7b5baf2d16f58560f641
