### ISSUE TITLE
Upgrade default jdk_version to 8

### ISSUE THREAD

**Issue by patcon** [ramonskie/bamboo#22]
Seems 1.7 is being deprecated: https://confluence.atlassian.com/display/BAMBOO/Supported+platforms

**Comment by ramonskie** [comment]
yup i know
when i tested and released the new version i will set the jdk as wel
only issue is that the openjdk 8 is not available in the default ubuntu repo yet

**Comment by ramonskie** [comment]
done in 
https://github.com/ramonskie/bamboo/commit/1fd28ec0ea316ff27e9b3c3e264e67187020aedd
