### ISSUE TITLE
vagrant is failing when chef-solo used and "issues_url" and "source_url" defined inside metadata.rb

### ISSUE THREAD

**Issue by vtty0** [ramonskie/bamboo#46]
Hello.
When I run vagrant and chef-solo it fails with error:

```
==> test-machine: Chef Client failed. 0 resources updated in 7.335532092 seconds
==> test-machine: [2016-06-27T09:30:54+00:00] ERROR: undefined method `issues_url' for #<Chef::Cookbook::Metadata:0x00000001ce8528>
==> test-machine: [2016-06-27T09:30:54+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

This can be fixed by replacing this stuff inside metadata.rb:
`
issues_url       'https://github.com/ramonskie/bamboo/issues'
source_url       'https://github.com/ramonskie/bamboo.git'
`

with this:

`
issues_url       'https://github.com/ramonskie/bamboo/issues' if respond_to?(:issues_url)
source_url       'https://github.com/ramonskie/bamboo.git' if respond_to?(:source_url)
`

----
Regards,
vtty0

**Comment by ramonskie** [comment]
pull request was merged
