### ISSUE TITLE
Vulnerable version

### ISSUE THREAD

**Issue by jopelope** [ramonskie/bamboo#48]
Hello ramonskie,

there is a known vulnerability in the bamboo version that is currently used here: https://confluence.atlassian.com/bamboo/bamboo-security-advisory-2016-07-20-831660461.html

I know that it is possible to change the version via attributes, but I still think it would be great to update the receipe.

Thanks!

**Comment by ramonskie** [comment]
thanks for pointing it out
i will release it with the latest release next week after i have done some testing
